export default [
	{ name: "Python",                    emojis: ["🐍", "🖥️"] },
	{ name: "HTML",                      emojis: ["🌐", "🛠️"] },
	{ name: "S/CSS",                     emojis: ["🖌️", "🎨", "🖼️"] },
	{ name: "Animation",                 emojis: ["🏃🏻‍♂️", "💨", "🥇"] },
	{ name: "Javascript",                emojis: ["❤️", "🧡", "💛"] },
	{ name: "SvelteKit",                 emojis: ["🧨", "💥", "🔥"] },
	{ name: "Django",                    emojis: ["🐍", "🌐"] },
	{ name: "React",                     emojis: ["⚛️", "💻", "📱"] },
	{ name: "UI/UX Design",              emojis: ["🖌️", "🎨", "🖼️"] },
	{ name: "SaaS",                      emojis: ["☁️", "💼", "🖥️"] },
	{ name: "GIT",                       emojis: ["🕸️", "💾"] },
	{ name: "API",                       emojis: ["☁️", "📤", "📩"] },
	{ name: "CMS",                       emojis: ["📝", "🗃️", "💻"] },
	{ name: "Wordpress",                 emojis: ["📝", "🗃️", "💻"] },
	{ name: "Lazy Loading",              emojis: ["⏳", "🔁", "🖼️"] },
	{ name: "Performance Optimizations", emojis: ["🎭", "🎩"] },
	{ name: "Mobile Optimizations",      emojis: ["📱", "🚀"] },
];
